//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int Id { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public System.DateTime Given_date { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Residence { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
