//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pledge_Agreement
    {
        public int Id { get; set; }
        public int Id_client { get; set; }
        public int Product_id { get; set; }
        public System.DateTime Date_contract { get; set; }
        public System.DateTime Date_return { get; set; }
        public int Commision { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
    }
}
