//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id_sale { get; set; }
        public int Id_product { get; set; }
        public System.DateTime Date_sale { get; set; }
        public int Margin { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
